//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyGearsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchandise_cart
    {
        public int id { get; set; }
        public string customerid { get; set; }
        public int merchandiseid { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> datebuy { get; set; }
        public bool incart { get; set; }
    
        public virtual merchandise_table merchandise_table { get; set; }
    }
}
