//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyGearsOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sgosdbEntities : DbContext
    {
        public sgosdbEntities()
            : base("name=sgosdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<merchandise_cart> merchandise_cart { get; set; }
        public virtual DbSet<merchandise_table> merchandise_table { get; set; }
        public virtual DbSet<merchandise_types> merchandise_types { get; set; }
    }
}
