//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyGearsOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchandise_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merchandise_table()
        {
            this.merchandise_cart = new HashSet<merchandise_cart>();
        }
    
        public int id { get; set; }
        public int idtype { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string About { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchandise_cart> merchandise_cart { get; set; }
        public virtual merchandise_types merchandise_types { get; set; }
    }
}
